mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
   path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    
]

mysite/polls/urls.py
from pipes import Template
from re import template
from django.urls import path
from django.views.generic import TemplateView

from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('danger/<int:guess>', views.danger, name='dangertest'),
    path('game/<slug:guess>',views.GameView.as_view()),
    path('main/<slug:guess>', views.mainView.as_view(), name = "main"),
    path('redirect', views.redirect, name="redirec"),
]

mysite/polls/models.py
from django.db import models

import datetime

from django.utils import timezone
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from http.client import ResponseNotReady
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.html import escape
from django.views import View
from django.urls import reverse, reverse_lazy

class mainView(View):
    def get(self, req, guess):
        res = '''
        <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>TESTING Class View</h1>
    <h2>''' + escape(guess) + ''' <h2>
    
</body>
</html>
        
        '''
        return HttpResponse(res)

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def danger(req,guess):
    return HttpResponse(''' <!DOCTYPE html>
<html>
<body>

<h1>My First Heading ''' + escape(guess) + '''test danger</h1>

<p>My first paragraph.</p>

</body>
</html>

test danger''')

def redirect(req):
    return HttpResponseRedirect('https://www.google.com')

class GameView(View):
    def get(self, request, guess):
        indexLinke = reverse_lazy('polls:index')

        x = {'root':indexLinke}
        #x = {'guess' : int(guess)+11, 'test': '<b>bold<b>'}
        return render(request, 'polls/test.html', x)

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE TEMPLATE</title>
</head>
<body>
    <h1>BASETEMPLATE</h1> 
    {%block content%}{% endblock %}
    
</body>
</html>

mysite/polls/templates/polls/test.html
{%extends "polls/base.html" %}
{%block content%}
    <h1>TESTING TEMPLATES</h1>
    <a href="/polls/main/633">HARD CODED</a>
    <p>--------------------------</p>
    <a href= "{%url 'polls:main' 633%}">abc</a>
    <p>--------------------------------------------------------------------------------------</p>
    <h1><a href="{{root}}">INDEX ROOT</a></h1>
{% endblock %}